-- movie
create table movie (
       movie_id integer generated by default as identity,
        director varchar(50) not null,
        store_id varchar(255) not null,
        title varchar(300) not null,
        user_id varchar(255),
        primary key (movie_id)
    )
    
-- store
create table store (
       store_id integer generated by default as identity,
        primary key (store_id)
    )
    
-- users
create table users (
       user_id integer generated by default as identity,
        email varchar(100) not null,
        name varchar(100) not null,
        password varchar(20) not null,
        primary key (user_id)
    )
    
-- foreign keys / constraints
    alter table movie 
       add constraint store_constraint 
       foreign key (store_id) 
       references store 
       
    alter table movie 
       add constraint user_constraint 
       foreign key (user_id) 
       references users
